### ISSUE TITLE
Can't handle files without path

### ISSUE THREAD

**Issue by ukch** [patrikaxelsson/zip2gz#1]
I have a zip file containing a single file, with a filename but no path. Running `zip2gz` on the file gives me the following traceback:

``` python-traceback
Traceback (most recent call last):
  File "$HOME/bin/zip2gz", line 41, in <module>
    dirName, fileName = zipInfo.filename.rsplit("/", 1)
ValueError: need more than 1 value to unpack
```

I guess this should return a path of `.`, or something.

**Comment by ukch** [comment]
I have successfully found a fix for this issue using `os.path.split` instead of `rsplit`.

**Comment by patrikaxelsson** [comment]
Thanks for the report, I have pushed a fix.

Used your suggestion, but used posixpath.split() as zip files are defined to always have forward slashes as path separator. I know for example ntpath handles forward slashes also, but this will give a consistent behaviour disregarding platform.

Also changed the other instances of platform-dependent path handling in the code to use os.path, which also made it more readable :).
